export const FETCH_PHONES_INIT = 'FETCH_PHONES_INIT';
export const FETCH_PHONES_SUCCESS = 'FETCH_PHONES_SUCCESS';
export const FETCH_PHONES_FAILED = 'FETCH_PHONES_FAILED';
export const FETCH_PHONE_ID_INIT = 'FETCH_PHONE_ID_INIT';
export const FETCH_PHONE_ID_SUCCESS = 'FETCH_PHONE_ID_SUCCESS';
export const FETCH_PHONE_ID_FAILED = 'FETCH_PHONE_ID_FAILED';
